name: Get Cache Dependencies
description: This action caches Node.js dependencies to speed up workflow runs
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
