name: Get Cache Dependencies
description: This action caches Node.js dependencies to speed up workflow runs
inputs: 
  caching: 
    description: Whethere to cache dependencies
    required: false
    default: 'true'
outputs:
  used-cache:
    description: Whether the cache was hit
    value: ${{ steps.install.output.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      uses: actions/cache@v4
      with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.caching != 'true'
      id: install
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash
